const {chromium}=require(process.env.LOCALAPPDATA+'/npm-cache/_npx/e41f203b7505f1fb/node_modules/playwright-core');const fs=require('fs');const assert=require('assert');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:1440,height:900}});const results=[];const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:3113',{waitUntil:'networkidle'});
for(const id of ['about','skill','project','design','contact']){await p.locator(`header a[href="/#${id}"]:visible`).click();await p.waitForTimeout(250);assert(new URL(p.url()).hash==='#'+id);results.push({anchor:id,top:await p.locator('#'+id).evaluate(e=>e.getBoundingClientRect().top)});}
await p.goto('http://localhost:3113');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent.trim()),'Home');assert.equal(await p.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle),'solid');
for(const name of ['HTML','CSS','JavaScript','React']){const button=p.getByRole('button',{name,exact:true});await button.focus();await p.keyboard.press('Enter');assert.equal(await button.getAttribute('aria-pressed'),'true');results.push({demo:name,preview:await p.locator('#hero-browser-preview').innerText()});}
const check=p.locator('#hero-browser-preview button');await check.focus();await p.keyboard.press('Space');assert.equal(await check.getAttribute('aria-pressed'),'true');await p.locator('button[class*="reset"]').click();assert.equal(await p.locator('button[aria-controls="hero-browser-preview"][aria-pressed="true"]').count(),0);
await p.setViewportSize({width:390,height:844});await p.locator('header button').focus();await p.keyboard.press('Enter');assert(await p.locator('#mobile-navigation').isVisible());await p.keyboard.press('Escape');assert(!(await p.locator('#mobile-navigation').isVisible()));assert.equal(await p.evaluate(()=>document.activeElement.tagName),'BUTTON');await p.locator('header button').click();await p.mouse.click(5,500);assert(!(await p.locator('#mobile-navigation').isVisible()));await p.locator('header button').click();await p.locator('#mobile-navigation a').first().click();assert(!(await p.locator('#mobile-navigation').isVisible()));
for(const slug of ['responsive-cafe','product-catalog','event-landing']){await p.goto('http://localhost:3113/work/'+slug);const next=p.locator('main a[href^="/work/"]').last();const href=await next.getAttribute('href');await next.focus();await p.keyboard.press('Enter');await p.waitForURL('**'+href);await p.locator('main header>a').click();await p.waitForURL('**/#project');}
for(const [name,width,height] of [['zoom200',640,450],['reflow400',320,720]]){await p.setViewportSize({width,height});await p.goto('http://localhost:3113');results.push({name,...await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,headerOverflow:[...document.querySelectorAll('header a,header button')].filter(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().right>innerWidth).length}))});await p.screenshot({path:`artifacts/interaction-audit/${name}.png`,fullPage:true});}
await p.emulateMedia({reducedMotion:'reduce'});await p.reload();await p.getByRole('button',{name:'JavaScript',exact:true}).click();results.push({reducedMotion:await p.locator('[class*="movingArt"]').evaluate(e=>getComputedStyle(e).animationName),lenis:await p.evaluate(()=>document.documentElement.className)});
results.push({errors});fs.writeFileSync('artifacts/interaction-audit/results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));await b.close()})().catch(e=>{console.error(e);process.exit(1)});

